version: '3.9'


services: 

#MongoDB services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db


# NodeJs API Services

  api: 
    build: .
    ports: 
      - 5000:4000
    command: sh -c "npm install -g nodemon && npm install && npm run dev "
    volumes:
      - .:/usr/src/app
    environment:
      PORT: 4000
      MONGO_URI: mongodb://mongo_db:27017
      DB_NAME: mainApp
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}